package cn.edu.cqu.DAO;

import cn.edu.cqu.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    List<ItemDO> listItem();

    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemDO record);
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}