package cn.edu.cqu.DAO;

import cn.edu.cqu.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    ItemStockDO selectByItemId(Integer itemId);
    ItemStockDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Mon Feb 10 17:30:29 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemStockDO record);
    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}