package cn.edu.cqu.DAO;

import cn.edu.cqu.dataobject.UserPwdDO;

public interface UserPwdDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jan 15 13:59:46 GMT+08:00 2020
     */
    int insert(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jan 15 13:59:46 GMT+08:00 2020
     */
    int insertSelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jan 15 13:59:46 GMT+08:00 2020
     */
    UserPwdDO selectByPrimaryKey(Integer id);

    /**
     * 此方法用于user_password中按照user_id获取UserPwdDO
     * @param userid
     * @return
     */
    UserPwdDO selectByUserId(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jan 15 13:59:46 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(UserPwdDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Wed Jan 15 13:59:46 GMT+08:00 2020
     */
    int updateByPrimaryKey(UserPwdDO record);
}